apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: siddhartha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result:after
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES
              value: "db"
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: siddhartha
spec:
  selector:
    app: result
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort
